---
- name: setup docker and run Dockerfiles

  # name of the host to run this on.
  hosts: default
  vars:

    # execute all commands as root
    ansible_become_user: root
    ansible_become_method: sudo
    ansible_become: true

  roles:
  - install_docker
  - docker_jenkins
  - docker_tomcat

