---
- name: setup docker and run Dockerfile

  # name of the host to run this on.
  hosts: default
  vars:

    # execute all commands as root
    ansible_become_user: root
    ansible_become_method: sudo
    ansible_become: true

  roles:
    # Only one role: Docker
  - install_docker
  - docker_jenkins
  - docker_tomcat

