---
  - name: install java 
    yum: name=java-1.7.0-openjdk update_cache=yes state=latest
    sudo: true

  - name: add group "tomcat"
    group: name=tomcat
    sudo: true

  - name: add user "tomcat"
    user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
    sudo: True

  - name: Download Tomcat
    get_url: url={{ tomcat_url }} dest={{ tomcat_download_dest }}/{{ tomcat_filename }}.tar.gz

  - name: Extract archive
    command: chdir=/usr/share /bin/tar xvf {{ tomcat_download_dest }}/{{ tomcat_filename }}.tar.gz -C {{ tomcat_install_dest }} creates={{ tomcat_install_dest }}/{{ tomcat_filename }}
    sudo: true

  - name: change permissions
    file: path={{ tomcat_install_dest }}/{{ tomcat_filename }} mode=0644
    sudo: true

  - name: Change ownership
    file: path={{ tomcat_install_dest }}/{{ tomcat_filename }} owner=tomcat group=tomcat state=directory recurse=yes
    sudo: true

  - name: Configure Tomcat server
    template: src=server.xml dest={{ tomcat_install_dest }}/{{ tomcat_filename }}/conf/
    notify: restart tomcat

  - name: Configure Tomcat users
    template: src=tomcat-users.xml dest={{ tomcat_install_dest }}/{{ tomcat_filename }}/conf/
    notify: restart tomcat

  - name: Start Tomcat
    service: name=tomcat state=started enabled=yes

  - name: wait for tomcat to start
    wait_for: port={{ tomcat_http_port }}
