---
- name: build jenkins docker image if needed
  command: docker build -t jenkins-ci /vagrant/dockerfiles/jenkins-ci/

# run docker jenkins container
# TODO running this as root. see dockerfile
# NOTE: force_kill: true means existing containers will be forcibly stopped
- name: run jenkins docker container
  docker_container:
    name: jenkins-ci-container
    image: jenkins-ci
    state: started
    ports: 8081:8081
    exposed: 8081
    recreate: true
    user: root
    detach: true

# wait until Jenkins has started
# http://stackoverflow.com/a/23957310/682912
- name: Wait untils Jenkins web API is available
  shell: curl --head --silent http://localhost:8081/cli/
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 10
  delay: 5

# get Jenkins CLI JAR
- name: download Jenkins CLI Jar
  command: wget http://localhost:8081/jnlpJars/jenkins-cli.jar
  args:
    chdir: /vagrant/dockerfiles/jenkins-ci/
    creates: /vagrant/dockerfiles/jenkins-ci/jenkins-cli.jar


# TODO this  does not work
# modify eth0 to allow building with Jenkins CLI without encountering the
# error "unexpected termination of channel"
# https://issues.jenkins-ci.org/browse/JENKINS-25858
# https://github.com/scala/scala-jenkins-infra/issues/26#issuecomment-73825006


# - name: modify eth0 to allow Jenkins CLI 
#   command: ethtool -K eth0 sg off

# - name: initiate first build of petclinic
#   command: java -jar jenkins-cli.jar -s http://localhost:8081 build petclinic-build -v -s
#   args:
#     chdir: /vagrant/dockerfiles/jenkins-ci/
