---

# process the Dockerfile template
- name: process the Dockerfile template
  template:
    src: Dockerfile.jenkins
    dest: /vagrant/dockerfiles/jenkins-ci/Dockerfile

- name: build jenkins docker image if needed
  command: docker build -t jenkins-ci /vagrant/dockerfiles/jenkins-ci/

- shell: docker images
  register: result

- debug: var=result verbosity=2

# run docker jenkins container
# TODO running this as root. see dockerfile
# bind-mounting /var/run/docker.sock from host to container in order to allow
# access to host's Docker Daemon from within container.

- name: run jenkins docker container
  docker_container:
    name: jenkins-ci-container
    image: jenkins-ci
    ports: "{{ jenkins_http_port }}:{{ jenkins_http_port }}"
    exposed: "{{ jenkins_http_port }}"
    recreate: true
    detach: true
    volumes: "/var/run/docker.sock:/var/run/docker.sock"

# get IP of Jenkins container
# http://stackoverflow.com/a/33457976/682912

- name: query IP of client container
  shell: "docker exec jenkins-ci-container hostname -I"
  register: _container_query

- name: get IP of query result
  set_fact:
    jenkins_ip: "{{ _container_query.stdout | regex_replace('\\s','') }}"

# wait until Jenkins has started
# http://stackoverflow.com/a/23957310/682912

- name: Wait untils Jenkins web API is available
  shell: curl --head --silent http://{{ jenkins_ip }}:{{ jenkins_http_port }}/cli/
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 10
  delay: 5

# get Jenkins CLI JAR

- name: download Jenkins CLI Jar
  command: wget http://{{ jenkins_ip }}:{{ jenkins_http_port }}/jnlpJars/jenkins-cli.jar
  args:
    chdir: /vagrant/dockerfiles/jenkins-ci/
    creates: /vagrant/dockerfiles/jenkins-ci/jenkins-cli.jar

- name: initiate first build of petclinic
  command: java -jar jenkins-cli.jar -s http://{{ jenkins_ip }}:{{ jenkins_http_port }} build petclinic-build -v -s
  args:
    chdir: /vagrant/dockerfiles/jenkins-ci/

- name: initiate first push of petclinic docker image
  command: java -jar jenkins-cli.jar -s http://{{ jenkins_ip }}:{{ jenkins_http_port }} build petclinic-docker -v -s
  args:
    chdir: /vagrant/dockerfiles/jenkins-ci/
