---
- name: build jenkins docker image if needed
  command: docker build -t jenkins-builder /vagrant/dockerfiles/jenkins-ci/

# run docker jenkins container
# TODO running this as root. see dockerfile
- name: run jenkins docker container
  docker_container:
    name: jenkins-ci-container
    image: jenkins-ci
    state: started
    ports: 8081:8081
    exposed: 8081
    recreate: true
    user: root


