---
- name: build docker image if needed
  command: docker build -t tomcat-webapp /vagrant/dockerfiles/tomcat-webapp/

- name: run tomcat docker container
  docker_container:
    name: tomcat-webapp-container
    image: tomcat-webapp
    state: started
    ports: 8080:8080
    exposed: 8080
    recreate: true

