---
# add Docker repo to get the latest docker
- name: add Docker repository
  yum_repository:
    name: docker
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg


    # update yum
- name: yum update
  yum:
    name: '*'
    state: latest

# install docker
- name: install docker
  yum:
    name: docker
    update_cache: yes
    state: latest
  notify: start docker service

# install docker-py as it is needed by docker-image
- name: install docker-py
  pip:
    name: docker-py
    state: present
  notify: start docker service

- name: add ec2 user to docker group
  # command: usermod -a -G docker ec2-user
  user:
    name: ec2-user
    groups: docker

- name: restart docker service
  service:
    name: docker
    state: restarted

- name: build docker image if needed
  command: docker build -t tomcat-webapp /vagrant/tomcat-webapp

- name: run docker container
  docker_container:
    name: tomcat-webapp-container
    image: tomcat-webapp
    state: started
    ports: 8080:8080
    exposed: 8080
    recreate: true
